admin/protected/models/LoginForm.php
<?php

/**
 * LoginForm class.
 * LoginForm is the data structure for keeping
 * user login form data. It is used by the 'login' action of 'SiteController'.
 */
class LoginForm extends CFormModel
{
	public $username;
	public $password;
	public $rememberMe;

	private $_identity;

	/**
	 * Declares the validation rules.
	 * The rules state that username and password are required,
	 * and password needs to be authenticated.
	 */
	public function rules()
	{
		return array(
			// username and password are required
			array('username, password', 'required'),
			// rememberMe needs to be a boolean
			array('rememberMe', 'boolean'),
			// password needs to be authenticated
			array('password', 'authenticate'),
		);
	}

	/**
	 * Declares attribute labels.
	 */
	public function attributeLabels()
	{
		return array(
			'username' => 'Nome de usuário',
			'password' => 'Senha',
			'rememberMe' => 'Lembre-se de mim',
		);
	}

	/**
	 * Authenticates the password.
	 * This is the 'authenticate' validator as declared in rules().
	 */
	public function authenticate($attribute,$params)
	{
		$this->_identity=new UserIdentity($this->username,$this->password);
		if(!$this->_identity->authenticate())
			$this->addError('password', 'Nome de usuário ou senha inválidos.');
	}

	/**
	 * Logs in the user using the given username and password in the model.
	 * @return boolean whether login is successful
	 */
	public function login()
	{
		if($this->_identity===null)
		{
			$this->_identity=new UserIdentity($this->username,$this->password);
			$this->_identity->authenticate();
		}
		if($this->_identity->errorCode===UserIdentity::ERROR_NONE)
		{
			$duration=$this->rememberMe ? 3600*24*30 : 0; // 30 days
			Yii::app()->user->login($this->_identity,$duration);
			return true;
		}
		else
			return false;
	}
}

admin/protected/controllers/HomeController.php
<?php

class HomeController extends Controller
{
	public function accessRules()
	{
		return array(
			array(
				'allow',
				'actions' => array('index', 'logout', 'error'),
				'users' => array('@'),
			),
			array(
				'allow',
				'actions' => array('error', 'login'),
				'users' => array('*'),
			),
		);
	}	
		
	public function actionIndex()
	{
		$this->redirect(Yii::app()->createUrl('post'));
	}
	
	public function actionError()
	{
		if ($error = Yii::app()->errorHandler->error) {
			if (Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}
	
	public function actionLogin()
	{
		$model = new LoginForm;
		
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'loginForm') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
		
		if (isset($_POST['LoginForm'])) {
			$model->attributes = $_POST['LoginForm'];
			if ($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		
		$this->render('login', array('model' => $model));
	}
	
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

admin/protected/controllers/PostController.php
<?php

class PostController extends Controller
{		
	public $searchForm = true;

	public function actions()
	{
		return array(
			'upload' => array(
				'class' => 'application.actions.UploadAction',
				'path' => Post::model()->getUploadBasePath('img'),
				'url' => Post::model()->getUploadBaseUrl('img'),
				'options' => array(
					'accept_file_types' => Post::model()->getUploadScopeAcceptFileTypes('img'),
					'image_versions' => array(		
						'thumbnail' => array(
							'max_width' => 140,
							'max_height' => 210,
						),
					),
				),
			),
		);
	}
	
	public function actionIndex($s = null)
	{
		$model = new Post('search');
		$model->unsetAttributes();
		
		if (isset($_GET['Post']))
			$model->setAttributes($_GET['Post']);
		else 
			$model->s = $s;
		
		$this->render('index', array('model' => $model));
	}
	
	public function actionCreate()
	{
		$model = new Post;

		if(isset($_POST['Post'])) {
			$model->setAttributes($_POST['Post']);

			if ($model->save()) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
					'<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');

				$this->redirect(array('update', 'id' => $model->id));
			}
		}

		$this->render('create', array('model' => $model));
	}

	public function actionUpdate($id)
	{
		$model = $this->loadModel('Post');

		if (isset($_POST['Post'])) {
			$model->setAttributes($_POST['Post']);

			if ($model->save()) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
					'<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');

				$this->refresh();
			}
		}

		$this->render('update', array('model' => $model));
	}
	
	public function actionDelete($id)
	{
		if (Yii::app()->request->isPostRequest) {
			// we only allow deletion via POST request
			$this->loadModel('Post', $id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if (!Yii::app()->request->isAjaxRequest) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
					'<strong>Sucesso!</strong> O registro foi excluído com sucesso.');		

				$this->redirect(array('index'));
			}
		} else
			throw new CHttpException(400, 'Requisição inválida. Por favor, não repita esta requisição novamente.');
	}

	public function actionChangeImg($id, $img)
	{
		$model = $this->loadModel('Post', $id);	
		$model->img = $img;

		if ($model->save())
			Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
				'<strong>Sucesso!</strong> A imagem foi alterada com sucesso.');		

		$this->redirect($this->createUrl('update', array('id' => $model->id)));
	}

	public function actionListImg($id)
	{
		$model = $this->loadModel('Post');
		$imgs = array();

		foreach ($model->getFiles('img') as $i => $file) {
			$obj = new stdClass();
			$obj->image = $file->url;
			$obj->title = $file->name;
			$imgs[$i] = $obj;
		}	

		foreach ($model->getFiles('img', 'thumbnail') as $i => $file) {
			$imgs[$i]->thumb = $file->url;
		}

		echo CJSON::encode($imgs);
	}
}

admin/protected/controllers/UserController.php
<?php

class UserController extends Controller
{	
	public $searchForm = true;
		
	public function accessRules()
	{
		return CMap::mergeArray(array(
			array(
				'allow',
				'actions' => array('alterarSenha'),
				'users' => array('@'),
			),
		), parent::accessRules());
	}
	
	public function actionIndex($s = null)
	{
		$model = new User('search');
		$model->unsetAttributes();

		if (isset($_GET['User']))
			$model->setAttributes($_GET['User']);
		else 
			$model->s = $s;
		
		$this->render('index', array('model' => $model));
	}
	
	public function actionCreate()
	{
		$model = new User;

		if(isset($_POST['User'])) {
			$model->setAttributes($_POST['User']);

			if ($model->save()) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
					'<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');

				$this->redirect(array('update', 'id' => $model->id));
			}
		}

		$this->render('create', array('model' => $model));
	}

	public function actionUpdate($id)
	{
		$model = $this->loadModel('User');

		if (isset($_POST['User'])) {
			$model->setAttributes($_POST['User']);

			if ($model->save()) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
					'<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');

				$this->refresh();
			}
		}

		$this->render('update', array('model' => $model));
	}
	
	public function actionDelete($id)
	{
		if (Yii::app()->request->isPostRequest) {
			// we only allow deletion via POST request
			$this->loadModel('User', $id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if (!Yii::app()->request->isAjaxRequest) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, 
					'<strong>Sucesso!</strong> O registro foi excluído com sucesso.');	

				$this->redirect(array('index'));
			}
		} else
			throw new CHttpException(400, 'Requisição inválida. Por favor, não repita esta requisição novamente.');
	}
}

admin/protected/views/home/error.php
<?php $this->pageTitle = 'Erro ' . $code; ?>

<p class="error alert alert-error"><?php echo CHtml::encode($message); ?></p> 

admin/protected/views/home/login.php
<?php $this->pageTitle = 'Login'; ?>	

<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id' => 'loginForm',
	'enableClientValidation' => true,
	'clientOptions' => array(
		'validateOnSubmit' => true,
	),
	'focus' => array($model, 'username'),
)); ?>

<div class="page-header text-center">
	<h1><?php echo $this->pageTitle; ?></h1>
</div>

<?php echo $form->errorSummary($model); ?>

<div class="panel">
	<?php echo $form->labelEx($model, 'username'); ?>

	<?php echo $form->textField($model, 'username', array('required' => 'required')); ?>
	
	<span class="hide"><?php echo $form->error($model, 'username'); ?></span>

	<?php echo $form->labelEx($model, 'password'); ?>

	<?php echo $form->passwordField($model, 'password', array('required' => 'required')); ?>
	
	<span class="hide"><?php echo $form->error($model, 'password'); ?></span>

	<div class="form-actions">
	 	<label class="checkbox pull-left">
	    	<?php echo $form->checkBox($model, 'rememberMe'); ?>
	    	<?php echo $model->getAttributeLabel('rememberMe'); ?>
		</label>

		<?php echo TbHtml::button('Entrar', array(
			'type' => 'submit',
			'color' => TbHtml::BUTTON_COLOR_PRIMARY,
			'class' => 'pull-right',
		)); ?>	
	</div>
</div>

<?php $this->endWidget(); ?>

admin/protected/views/layouts/main.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="pt-br" />
	<title><?php echo Yii::app()->name; ?> | <?php echo CHtml::encode($this->pageTitle); ?></title>

	<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/bootstrap.css'); ?>
	<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/bootstrap-responsive.css'); ?>
	<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/main.css'); ?>	

	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body class="ctrl-<?php echo $this->id . ' act-' . $this->action->id; ?>">
	
<?php if (!Yii::app()->user->isGuest) : ?>
	
<?php $this->widget('bootstrap.widgets.TbNavbar', array(
	'brandLabel' => CHtml::encode(Yii::app()->name),
	'brandUrl' => Yii::app()->createUrl('home/index'),
	'color' => TbHtml::NAVBAR_COLOR_INVERSE,
	'collapse' => true,
	'items' => array(
		array(
			'class' => 'bootstrap.widgets.TbNav',
			'items' => array(
				array(
					'label' => 'Posts',
					'url' => array('/post'),
				),
				array(
					'label' => 'Usuários',
					'url' => array('/user'),
				),
			),
		),	
		array(
			'class' => 'bootstrap.widgets.TbNav',
			'htmlOptions' => array('class' => 'pull-right'),
			'items' => array(
				TbHtml::navbarMenuDivider(),	
				array(
					'icon' => TbHtml::ICON_COG,
					'items' => array(
						array(
							'label' => 'Perfil',
							'icon' => TbHtml::ICON_USER,
							'url' => array('/user/update', 'id' => Yii::app()->user->id),
						),
						TbHtml::menuDivider(),						
						array(
							'label' => 'Sair',
							'icon' => TbHtml::ICON_OFF,
							'url' => array('/home/logout'),
						),						
					),
				),
				TbHtml::navbarMenuDivider(),
			),
		),
	),
)); ?>
	
<div id="header">
	<div class="container">
		<h1 class="pull-left"><?php echo $this->pageTitle; ?> <small><?php echo $this->pageSubtitle; ?></small></h1>
		<?php if ($this->searchForm || $this->menu) : ?>		
		<div class="well pull-right">
			<?php if ($this->searchForm) {
				echo TbHtml::beginFormTb(TbHtml::FORM_LAYOUT_SEARCH, $this->createUrl('index'), 'get');
				echo TbHtml::textField('s', Yii::app()->request->getParam('s'), 
					array('class' => 'search-query', 'placeholder' => 'Pesquisar', 'autocomplete' => 'false'));
				echo TbHtml::submitButton(TbHtml::icon(TbHtml::ICON_SEARCH, array('color' => TbHtml::ICON_COLOR_WHITE)), 
					array('color' => TbHtml::BUTTON_COLOR_LINK, 'name' => false));
				echo TbHtml::endForm();
			} 
			foreach ($this->menu as $items) {
				echo TbHtml::buttonToolbar(array(array(
					'items' => $items, 
					'color' => TbHtml::BUTTON_COLOR_INVERSE, 
				)));
			} ?>
		</div>
		<?php endif; ?>
	</div>
</div>

<?php endif; ?>

<div id="content">
	<div class="container">
		<?php $this->widget('bootstrap.widgets.TbAlert'); ?>
		<?php echo $content; ?>
	</div>
</div>

<div id="ajax-loading"></div>

<?php Yii::app()->clientScript->registerCoreScript('jquery'); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/bootstrap.js', CClientScript::POS_END); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/main.js', CClientScript::POS_END); ?>

</body>
</html>

admin/protected/views/post/_form.php
<?php $files = $model->getFiles('img', 'thumbnail'); ?>

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id' => 'userForm',
	'layout' => TbHtml::FORM_LAYOUT_HORIZONTAL,
)); ?>

<?php echo $form->errorSummary($model); ?>

<?php ob_start(); ?>

<div class="control-group">
	<?php echo $form->labelEx($model, 'img', array('class' => 'control-label')); ?>
	<div class="controls">
		<?php if ($files) : ?>
		<ul class="thumbnails inline" style="margin-bottom: 0;">
			<?php foreach ($files as $file) : ?>		
			<li>
				<?php if ($model->img === $file->name) : ?>
				<?php echo CHtml::link($file->render, $this->createUrl('changeImg', array(
					'id' => $model->id,
					'img' => '',
				)), array('class' => 'thumbnail active')); ?>
				<?php else : ?>
				<?php echo CHtml::link($file->render, $this->createUrl('changeImg', array(
					'id' => $model->id,
					'img' => $file->name,
				)), array('class' => 'thumbnail')); ?>
				<?php endif; ?>
			</li>
			<?php endforeach; ?>
		</ul>
		<p class="help-inline">Clique sobre uma imagem para defini-la como principal.</p>
		<?php elseif ($model->isNewRecord) : ?>
		<p class="alert alert-info" style="margin-bottom: 0;">Salve o registro para habilitar o envio de imagens.</p>
		<?php else : ?>
		<p class="alert alert-info" style="margin-bottom: 0;">Clique em Upload para enviar imagens.</p>	
		<?php endif; ?>
		<?php echo $form->error($model, 'img'); ?>
	</div>
</div>	

<?php echo $form->dropDownListControlGroup($model, 'status', Lookup::items('PostStatus')); ?>

<?php echo $form->textFieldControlGroup($model, 'categories', array(
	'data-mode' => 'multiple',
	'data-provide' => 'typeahead',
	'data-source' => CJSON::encode(Category::model()->suggestCategories('Post', '', -1)),
	'autocomplete' => 'off',
)); ?>

<?php echo $form->textFieldControlGroup($model, 'title'); ?>

<div class="control-group">
	<?php echo $form->labelEx($model, 'content', array('class' => 'control-label')); ?>
	<div class="controls">
		<?php $this->widget('ext.imperavi-redactor-widget.ImperaviRedactorWidget', array(
		    'model' => $model,
		    'attribute' => 'content',
		    'options' => array(
		        'lang' => Yii::app()->language,
				'imageGetJson' => Yii::app()->createUrl('post/listImg', array('id' => $model->id)),
		    ),
		)); ?>
		<?php echo $form->error($model, 'content'); ?>
	</div>
</div>

<div class="form-actions">
	<?php echo TbHtml::button('Salvar', array(
		'type' => 'submit',
		'color' => TbHtml::BUTTON_COLOR_PRIMARY,
		'icon' => TbHtml::ICON_OK,
	)); ?>	

	<?php echo TbHtml::linkButton('Cancelar', array(
		'type' => 'link',
		'url' => array('index'),
		'color' => TbHtml::BUTTON_COLOR_LINK,
	)); ?>
</div>
	
<?php $this->endWidget(); ?>

<?php $tabs[] = array(
	'label' => 'Post' . ($model->hasErrors() ? ' ' . TbHtml::tag('span', array('class' => 'badge badge-important'), '!') : ''),
	'content' => ob_get_contents(),
	'active' => true,
); ob_end_clean(); ?>

<?php $tabs[] = array(
	'label' => 'Upload',
	'visible' => !$model->isNewRecord,
	'content' => $this->renderPartial('_upload', array('model' => $model), true),
); ?>

<?php $this->widget('bootstrap.widgets.TbTabs', array(
	'id' => 'postFormTabs',
	'tabs' => $tabs,
)); ?>

<?php 
$js = <<<EOD
$('#postFormTabs .nav > li:first > a').on('click', function () {
	location.reload()
})
EOD;

Yii::app()->clientScript->registerScript('postForm', $js); ?>

admin/protected/views/post/_upload.php
<p><i class="icon icon-info-sign"></i> Evite enviar images com nomes contendo espaços, acentos ou 
caracteres especiais (Ç, !, ?, etc.), assim como nomes muito  longos (máximo 128 caracteres). 
São aceitos arquivos com as seguintes extensões: <strong>.gif, .jpg e .png</strong>.</p> 

<?php $this->widget('application.widgets.Upload', array(
	'id' => 'post',
	'url' => $this->createUrl('upload', array('folder' => $model->getUploadModelFolder())),
	/*
	'options' => array(
		'maxNumberOfFiles' => 1,
	),
	*/
)); ?>

admin/protected/views/post/create.php
<?php 
$this->pageTitle = 'Post';
$this->pageSubtitle = 'Incluir';
?>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>

admin/protected/views/post/index.php
<?php 
$this->pageTitle = 'Posts';
$this->menu = array(
	array(
		array(
			'label' => 'Incluir',
			'icon' => 'file',
			'url' => array('create'),
		),
	),
); ?>

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id' => 'postGrid',
	'type' => array(TbHtml::GRID_TYPE_STRIPED, TbHtml::GRID_TYPE_BORDERED),
	'dataProvider' => $model->search(),
	'columns' => array(
		'id',
		array(
			'name' => 'status',
			'value' => 'Lookup::item("PostStatus", $data->status)',
			'filter' => Lookup::items('PostStatus'),
		),
		'title',
		'tags',
		'categories',
		array(
			'name' => 'update_time',
			'value' => 'date("d/m/Y h:m", $data->update_time)',
		),	
		array(
			'class' => 'bootstrap.widgets.TbButtonColumn',
			'template' => "{update}\n{delete}",
		),
	),
)); ?>

admin/protected/views/post/update.php
<?php 
$this->pageTitle = 'Post';
$this->pageSubtitle = 'Editar (' . CHtml::encode($model->title) . ')';
$this->menu = array(
	array(
		array(
			'label' => 'Excluir',
			'icon' => TbHtml::ICON_TRASH,
			'color' => TbHtml::BUTTON_COLOR_DANGER,
			'url' => '#',
			'htmlOptions' => array(
				'submit' => array('delete', 'id' => $model->id),
				'confirm' => 'Tem certeza que deseja excluir este registro?',
			),
		),
	),
); ?>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>

admin/protected/views/user/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id' => 'userForm',
	'layout' => TbHtml::FORM_LAYOUT_HORIZONTAL,
)); ?>

<?php echo $form->errorSummary($model); ?>

<div class="row-fluid">
	<div class="span6">
		<?php echo $form->textFieldControlGroup($model, 'name'); ?>
	</div>
	<div class="span6">
		<?php echo $form->textFieldControlGroup($model, 'username'); ?>
	</div>
</div>

<div class="row-fluid">
	<div class="span6">
		<?php echo $form->passwordFieldControlGroup($model, 'newPassword'); ?>
	</div>
	<div class="span6">
		<?php echo $form->passwordFieldControlGroup($model, 'newPasswordRepeat'); ?>
	</div>
</div>

<div class="form-actions">
	<?php echo TbHtml::button('Salvar', array(
		'type' => 'submit',
		'color' => TbHtml::BUTTON_COLOR_PRIMARY,
		'icon' => TbHtml::ICON_OK,
	)); ?>	

	<?php echo TbHtml::linkButton('Cancelar', array(
		'type' => 'link',
		'url' => array('index'),
		'color' => TbHtml::BUTTON_COLOR_LINK,
	)); ?>
</div>
	
<?php $this->endWidget(); ?>

admin/protected/views/user/create.php
<?php 
$this->pageTitle = 'Usuário';
$this->pageSubtitle = 'Incluir';
?>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>

admin/protected/views/user/index.php
<?php 
$this->pageTitle = 'Usuários';
$this->menu = array(
	array(
		array(
			'label' => 'Incluir',
			'icon' => 'file',
			'url' => array('create'),
		),
	),
); ?>

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id' => 'userGrid',
	'type' => array(TbHtml::GRID_TYPE_STRIPED, TbHtml::GRID_TYPE_BORDERED),
	'dataProvider' => $model->search(),
	'columns' => array(
		'id',
		'name',	
		'username',
		array(
			'class' => 'bootstrap.widgets.TbButtonColumn',
			'template' => "{update}\n{delete}",
		),
	),
)); ?>

admin/protected/views/user/update.php
<?php 
$this->pageTitle = 'Usuário';
$this->pageSubtitle = 'Editar (' . CHtml::encode($model->name) . ')';
$this->menu = array(
	array(
		array(
			'label' => 'Excluir',
			'icon' => TbHtml::ICON_TRASH,
			'color' => TbHtml::BUTTON_COLOR_DANGER,
			'url' => '#',
			'htmlOptions' => array(
				'submit' => array('delete', 'id' => $model->id),
				'confirm' => 'Tem certeza que deseja excluir este registro?',
			),
		),
	),
); ?>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>