protected/models/ContatoForm.php
<?php

class ContatoForm extends CFormModel
{
	public $nome;
	public $telefone;
	public $email;
	public $mensagem;

	public function rules()
	{
		return array(
			array('nome, email, mensagem', 'required'),
			array('email', 'email'),
			array('telefone', 'safe'),
		);
	}

	public function attributeLabels()
	{
		return array(
			'nome' => 'Seu nome',
			'telefone' => 'Telefone',
			'email' => 'Seu e-mail',	
			'mensagem' => 'Mensagem',
		);
	}

	public function submit()
	{
		$from = Yii::app()->params['mail.from'];
		$from = 'contato@bicalhoadv1.hospedagemdesites.ws';

		$headers  = "MIME-Version: 1.0\r\n";
		$headers .= "Content-Type: text/html; charset=utf-8\r\n";
		$headers .= "From: {$from}\r\n";
		$headers .= "Reply-To: {$this->email}\r\n";
		$headers .= "Return-Path: {$from}\r\n";
		$body  = "<style>";
		$body .= "table { width: 100%; font: normal 13px/20px Arial, sans-serif; }";
		$body .= "th, td { padding: 4px 8px; border-bottom: 1px solid #ddd; }";
		$body .= "th { width: 140px; text-align: left; }";
		$body .= "</style>";
		$body .= "<table>";
		$body .= "<tr>";
		$body .= "<th>{$this->getAttributeLabel('nome')}:</th>";
		$body .= "<td>{$this->nome}</td>";
		$body .= "</tr><tr>";
		$body .= "<th>{$this->getAttributeLabel('telefone')}:</th>";
		$body .= "<td>{$this->telefone}</td>";
		$body .= "</tr><tr>";
		$body .= "<th>{$this->getAttributeLabel('email')}:</th>";
		$body .= "<td>{$this->email}</td>";
		$body .= "</tr><tr>";
		$body .= "<th>{$this->getAttributeLabel('mensagem')}:</th>";
		$body .= "<td>{$this->mensagem}</td>";
		$body .= "</tr>";
		$body .= "</table>";
		
		return mail($from, 'Site > Contato', $body, $headers, "-r" . $from);
	}
}

protected/controllers/HomeController.php
<?php

class HomeController extends Controller
{	
	public function actionIndex()
	{
		$posts = Post::model()->findAll(array(
			'condition' => 'status = ' . Post::STATUS_PUBLISHED,
			'order' => 'update_time DESC',
			'limit' => 3,
		));

		$this->render('index', array('posts' => $posts));
	}

	public function actionContato()
	{
		$contatoForm = new ContatoForm;

		if (isset($_POST['ContatoForm'])) {
			$contatoForm->setAttributes($_POST['ContatoForm']);

			if ($contatoForm->validate() && $contatoForm->submit()) {
				Yii::app()->user->setFlash('success', 'Obrigado pelo contato. Responderemos a sua mensagem o mais breve possível.');
				$this->redirect(Yii::app()->homeUrl);				
			}
		}

		$this->render('contato', array('contatoForm' => $contatoForm));
	}
	
	public function actionError()
	{
		if ($error = Yii::app()->errorHandler->error) {
			if (Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

}

protected/controllers/PostController.php
<?php

class PostController extends Controller
{			
	private $_model;

	public function actionIndex()
	{
		$criteria = new CDbCriteria(array(
			'condition' => 'status = ' . Post::STATUS_PUBLISHED,
			'order' => 'update_time DESC',
		));

		if (isset($_GET['category']))
			$criteria->addSearchCondition('categories', Category::unfriendlyName($_GET['category']));

		if (isset($_GET['tag']))
			$criteria->addSearchCondition('tags', Tag::unfriendlyName($_GET['tag']));

		if (isset($_GET['year']) && isset($_GET['month'])) {
			$timestamp = strtotime($_GET['year'] . '-' . $_GET['month'] . '-00');
			$criteria->compare('update_time', '> ' . $timestamp);
			$criteria->compare('update_time', '< ' . ($timestamp + 2629743), 'AND');
		}

		if (isset($_GET['name']))
			$criteria->addSearchCondition('name', $_GET['name']);

		if (isset($_GET['s'])) {
			$criteria->compare('title', $_GET['s'], true);
			$criteria->compare('content', $_GET['s'], true, 'OR');
		}

		$dataProvider = new CActiveDataProvider('Post', array(
			'pagination' => false,
			'criteria' => $criteria,
		));

		$this->render('index', array('dataProvider' => $dataProvider));
	}

	public function actionView($id)
	{
		$post = Post::model()->find(array(
			'condition' => 'id = :id OR name = :id',
			'params' => array(':id' => $id),
		));

		if ($post === null)
			$this->redirect($this->createUrl('/home'));

		$this->render('view', array('post' => $post));
	}

	public function renderCategoryNav()
	{
		$items = array();

		foreach (Category::model()->suggestCategories('Post', '') as $category) {
			$categoryName = Category::friendlyName($category);
			$items[] = array(
				'label' => CHtml::encode($category),
				'url' => $this->createUrl('/post/index', array('category' => $categoryName)),
				'active' => isset($_GET['category']) && $_GET['category'] === $categoryName,
			);
		}

		$this->renderPartial('_categoryNav', array('items' => $items));
	}

	public function renderArchiveNav()
	{
		$models = Post::model()->findAll(array(
			'condition' => 'status = ' . Post::STATUS_PUBLISHED,
			'order' => 'update_time DESC',
		));

		$dates = array();

		foreach ($models as $model) {
			$date = date('Y-m-01', $model->update_time);
			if (!in_array($date, $dates))
				$dates[] = $date;
		}

		$items = array();

		foreach ($dates as $date) {
			$dateExploded = explode('-', $date);
			$year = $dateExploded[0];
			$month = $dateExploded[1];
			$items[] = array(
				'label' => ucfirst(Yii::app()->dateFormatter->format('MMMM', $date)) . '/' . $year,
				'url' => $this->createUrl('/post/index', array(
					'year' => $year,
					'month' => $month,
				)),
				'active' => isset($_GET['year']) && isset($_GET['month'])
					&& $_GET['year'] === $year && $_GET['month'] === $month,
			);
		}

		$this->renderPartial('_archiveNav', array('items' => $items));
	}
}

protected/views/home/_contatoForm.php
<?php 
$contatoForm = isset($contatoForm) ? $contatoForm : new ContatoForm;
$form = $this->beginWidget('CActiveForm', array(
	'id' => 'contatoForm',
	'method' => 'post',
	'action' => array('/home/contato'),
)); 
?>

<?php echo $form->errorSummary($contatoForm, '<div class="bg-primary" style="padding: 20px 20px 10px; margin: 20px 0;">', '</div>'); ?>

<div class="form-group">
	<?php echo $form->textField($contatoForm, 'nome', array(
		'class' => 'form-control',  
		'placeholder' => $contatoForm->getAttributeLabel('nome'),
	)); ?>
</div>

<div class="form-group">
	<?php echo $form->textField($contatoForm, 'telefone', array(
		'class' => 'form-control', 
		'placeholder' => $contatoForm->getAttributeLabel('telefone'),
	)); ?>
</div>

<div class="form-group">
	<?php echo $form->textField($contatoForm, 'email', array(
		'class' => 'form-control', 
		'placeholder' => $contatoForm->getAttributeLabel('email'),
	)); ?>
</div>

<div class="form-group">
	<?php echo $form->textArea($contatoForm, 'mensagem', array(
		'class' => 'form-control',
		'rows' => 4,
		'placeholder' => $contatoForm->getAttributeLabel('mensagem'),
	)); ?>
</div>

<div class="form-group text-right">
	<?php echo CHtml::button('Corrigir', array('type' => 'reset', 'class' => 'btn btn-primary btn-lg')); ?>
	<?php echo CHtml::button('Enviar', array('type' => 'submit', 'class' => 'btn btn-primary btn-lg')); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/home/_view.php
<?php 
$categoryLinks = $data->getCategoryLinks(); 
?>

<article class="post">
	<header class="post-header">
		<h2 class="post-title"><?php echo CHtml::encode($data->title); ?></h2>	
		<div class="post-meta"> 
			<span class="post-author">Escrito por: <b><?php echo CHtml::encode($data->author->name); ?></b></span>
			<span class="post-create-time">em <b><date datetime="<?php echo date('Y-m-d', $data->create_time); ?>"><?php echo date('d/m/Y', $data->create_time); ?></date></b></span>
			<?php if ($data->update_time > $data->create_time) : ?>
			&ndash;
			<span class="post-update-time">Atualizado em: <date datetime="<?php echo date('Y-m-d', $data->update_time); ?>"><?php echo date('d/m/Y', $data->update_time); ?></date></span>
			<?php endif; ?>	
			<?php if ($categoryLinks) : ?>
			&ndash;
			<span class="post-category-links"> 
				Categorias: 
				<?php foreach ($categoryLinks as $categoryLink) : ?>
					<?php echo $categoryLink; ?>
				<?php endforeach; ?>
			</span>
			<?php endif; ?>
		</div>
	</header>
	<?php $file = $data->getFile('img', null, array('class' => 'post-img img-responsive')); ?>
	<?php echo $file ? $file->render : ''; ?>
	<div class="post-content">
		<?php echo $data->content; ?>
	</div>
</article>

protected/views/home/contato.php
<?php $this->pageTitle = 'Contato'; ?>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<?php echo $this->renderPartial('/home/_contatoForm', array('contatoForm' => $contatoForm)); ?>
	</div>
</div>

protected/views/home/error.php
<?php $this->pageTitle = 'Erro ' . $code; ?>

<p><?php echo CHtml::encode($message); ?></p> 

protected/views/home/index.php
<?php $this->pageTitle = 'Bem-vindo'; ?>

<section class="main-section" id="posts">
	<div class="container">
		<div class="main-section-header">
			<h1 class="main-section-title">Notícias <span class="fa fa-angle-down"></span></h1>
			<hr>
		</div>
		<div class="row">
			<?php for ($i = 0; $i < 3; $i++) : ?>
			<div class="col col-md-4">
				<?php if (isset($posts[$i])) : ?>
				<?php $this->renderPartial('/post/_view', array('data' => $posts[$i], 'displayContent' => true)); ?>
				<?php endif; ?>
			</div>
			<?php endfor; ?>
		</div>
	</div>
</section>	

<section class="main-section" id="quem-somos">
	<div class="container">
		<div class="main-section-header">
			<h1 class="main-section-title">Quem Somos <span class="fa fa-angle-down"></span></h1>
			<hr>
		</div>
		<div class="row">
			<div class="col-md-5">
				<p><img class="img-responsive" src="img/palacio-da-justica.jpg"></p>
				<br>
				<blockquote>
					<p><span class="h4">"Tem fé no Direito como o melhor instrumento para a convivência humana. Na Justiça, como destino normal do Direito. Na Paz, como substituto bondoso da Justiça. E, sobretudo, tem fé na Liberdade, sem a qual não há Direito, nem Justiça, nem Paz"</span></p>
					<footer><cite title="Eduardo J. Couture">Eduardo J. Couture</cite></footer>
				</blockquote>
			</div>
			<div class="col-md-7">
				<p>Bicalho & Bicalho é uma sociedade de advogados do interior paulista, localizada em Salto, a 100 km da cidade de São Paulo, e registrada na OAB/SP sob o nº. 18.757.</p> 
				<p>O escritório é integrado por toda uma família de advogados, atuando há <?php echo (date('Y') - 1996); ?> anos nas diversas áreas do Direito, especialmente na Cível, Trabalhista, Sindical, Empresarial, Tributária e Previdenciária.</p>
				<p>Foi fundado pelo advogado Dr. Romeu Gonçalves Bicalho, em janeiro de 1996, e funciona à rua Prudente de Moraes, 793 – Centro – Salto.</p>
				<br><br class="visible-xs visible-sm">
				<div class="main-section-header">
					<h2 class="main-section-title">Área de Atuação</h2>
					<hr>
				</div>
				<div class="row text-uppercase">
					<div class="col-xs-6">
						<ul>
							<li>Direito Civil</li>
							<li>Direito de Família</li>
							<li>Direito Empresarial</li>
						</ul>
					</div>
					<div class="col-xs-6">
						<ul>
							<li>Direito do Trabalho</li>
							<li>Direito do Consumidor</li>
							<li>Direito Previdenciário</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>	

<section class="main-section" id="corpo-juridico">
	<div class="container">
		<div class="main-section-header">
			<h1 class="main-section-title">Corpo Jurídico <span class="fa fa-angle-down"></span></h1>
			<hr>
		</div>
		<div class="row">
			<div class="col-md-5">
				<div class="media">
					<img class="pull-left" src="img/dr-romeu.jpg" alt="Dr. Romeu Gonçalves Bicalho">
					<div class="media-body">
						<h5>Dr. Romeu Gonçalves Bicalho</h5>
						<p>Advogado inscrito na OAB/SP sob nº. 138.816. Graduado em Direito pela Faculdade de Direito de Itu – FADITU.</p>
						<p>Doutor em Direito pela Pontifícia Universidade Católica de São Paulo - PUC-SP. Mestre em Direito pela Universidade Metodista de Piracicaba - UNIMEP.</p>
						<p>Co-autor das obras "Questões de Exame de Ordem - comentadas e "A Nova Execução de Títulos Executivos Extrajudiciais - análise prática", ambas da editora Método e de "Ensaios de Direito Internacional – Fundamentos, Novos Atores e Integração Regional ", pela editora Millennium.</p>
						<p>Acesse mais informações: <a href="http://lattes.cnpq.br/7623585991411751">http://lattes.cnpq.br/7623585991411751</a></p>
					</div>	
				</div>
				<hr class="visible-xs visible-sm">
			</div>
			<div class="col-md-7">
				<div class="media">
					<img class="pull-left" src="img/dr-ronaldo.jpg" alt="Dr. Ronaldo Gonçalves Bicalho">
					<div class="media-body">
						<h5>Dr. Ronaldo Gonçalves Bicalho</h5>
						<p>Advogado inscrito na OAB/SP sob no. 211.865. Formado pela Faculdade de Direito de Itu- FADITU. Especialista em Direto do Trabalho pela Faculdade de Direito de Itu - FADITU.</p>
					</div>
				</div>
				<hr>
				<div class="media">
					<img class="pull-left" src="img/dra-jane.jpg" alt="Dra. Jane Gonçalves Bicalho Agostinho">
					<div class="media-body">
						<h5>Dra. Jane Gonçalves Bicalho Agostinho</h5>
						<p>Advogada inscrita na OAB/SP sob no. 253.652. Formada pela Faculdade de Direito de Itu – FADITU. Especialista em Direito Previdenciário.</p>
					</div>
				</div>
				<hr>
				<div class="media">
					<img class="pull-left" src="img/dra-mirna.jpg" alt="Dra. Mirna Maria Scalet Bicalho">
					<div class="media-body">
						<h5>Dra. Mirna Maria Scalet Bicalho</h5>
						<p>Advogada inscrita na OAB/SP sob no. 276.335. Graduada em Direito pela Faculdade de Direito de Itu - FADITU e em Jornalismo pela Universidade Metodista de Piracicaba – UNIMEP.</p>
					</div>
				</div>
				<hr>
				<div class="media">
					<img class="pull-left" src="img/dra-patricia.jpg" alt="Dra. Patrícia Gonçalves Bicalho">
					<div class="media-body">
						<h5>Dra. Patrícia Gonçalves Bicalho</h5>
						<p>Advogada inscrita na OAB/SP sob no. 313.924. Formada pela Faculdade de Direito de Itu – FADITU.</p>
					</div>
				</div>
			</div>					
		</div>
	</div>
</section>	

protected/views/post/_archiveNav.php
<?php $this->widget('zii.widgets.CMenu', array(
	'id' => 'post-archive-nav',
	'items' => $items,
	'htmlOptions' => array(
		'class' => 'nav',
	),
)); ?>

protected/views/post/_banner.php
<img class="pull-right" src="<?php echo Yii::app()->baseUrl; ?>/img/banners/fique-por-dentro.png">
<div class="full-banner-body">
	<h1 class="full-banner-heading">Fique por dentro</h1>
	<p class="lead">Notícias de mercado, dicas, matérias e muitos outros assuntos relacionados a construção, decoração e reforma.</p>
</div>

protected/views/post/_categoryNav.php
<?php $this->widget('zii.widgets.CMenu', array(
	'id' => 'post-category-nav',
	'items' => $items,
	'htmlOptions' => array(
		'class' => 'nav',
	),
)); ?>

protected/views/post/_sidebar.php
<aside class="sidebar-aside">
	<h3 class="sidebar-aside-title">Pesquisar</h3>
	<form action="<?php echo $this->createUrl('/post'); ?>">
		<div class="input-group input-group-sm">
			<input type="text" class="form-control" name="s" value="<?php echo Yii::app()->request->getParam('s'); ?>" placeholder="Pesquisar..." autocomplete="false">
			<span class="input-group-btn">
				<button class="btn btn-default btn-primary" type="submit">Ir</button>
			</span>
		</div>
	</form>
</aside>

<aside class="sidebar-aside">
	<h3 class="sidebar-aside-title">Categorias</h3>
	<?php $this->renderCategoryNav(); ?>
</aside>

<aside class="sidebar-aside">
	<h3 class="sidebar-aside-title">Arquivo</h3>
	<?php $this->renderArchiveNav(); ?>
</aside>

protected/views/post/_view.php
<?php 
$categoryLinks = $data->getCategoryLinks(); 
$readMoreUrl = Yii::app()->createUrl('/post/view', array('id' => $data->name));
$readMoreLink = CHtml::link('[ + ]', $readMoreUrl, array(
	'title' => 'Continue lendo (' . CHtml::encode($data->title) . ')',
	'rel' => 'tooltip',
	'class' => 'read-more',
));	
?>

<article class="post">
	<header class="post-header">
		<?php if (!isset($hideTitle)) : ?>

		<?php if (isset($displayFullContent)) : ?>
		<h2 class="post-title"><?php echo CHtml::encode($data->title); ?></h2>	
		<?php else : ?>
		<h2 class="post-title">
			<a href="<?php echo $readMoreUrl; ?>">
				<?php echo CHtml::encode($data->title); ?>	
				<?php if (!isset($displayContent)) : ?>
				<i class="fa fa-external-link"></i>
				<?php endif; ?>
			</a>
		</h2>
		<?php endif; ?>

		<?php endif; ?>

		<div class="post-meta"> 
			<span class="post-author">Escrito por: <b><?php echo CHtml::encode($data->author->name); ?></b></span>
			<span class="post-create-time">em <b><date datetime="<?php echo date('Y-m-d', $data->create_time); ?>"><?php echo date('d/m/Y', $data->create_time); ?></date></b></span>
			<?php if ($data->update_time > $data->create_time) : ?>
			&ndash;
			<span class="post-update-time">Atualizado em: <date datetime="<?php echo date('Y-m-d', $data->update_time); ?>"><?php echo date('d/m/Y', $data->update_time); ?></date></span>
			<?php endif; ?>	
			<?php if ($categoryLinks) : ?>
			&ndash;
			<span class="post-category-links"> 
				Categorias: 
				<?php foreach ($categoryLinks as $categoryLink) : ?>
					<?php echo $categoryLink; ?>
				<?php endforeach; ?>
			</span>
			<?php endif; ?>
		</div>
	</header>

	<?php if (isset($displayImg)) : ?>
		
	<?php $file = $data->getFile('img', null, array('class' => 'post-img img-responsive')); ?>
	<?php echo $file ? $file->render : ''; ?>

	<?php endif; ?>

	<?php if (isset($displayFullContent)) : ?>

	<div class="post-content">
		<?php echo $data->content; ?>
	</div>

	<?php elseif (isset($displayContent)) : ?>

	<div class="post-excerpt">
		<?php $content = ''; ?>

		<?php $content = $this->widget('ext.XReadMore', array(
			'model' => $data,
			'attribute' => 'content',
			'maxChar' => 400,
			'showLink' => false,
		), true); ?>

		<?php $content .= ' ' . $readMoreLink; ?>	

		<?php echo $content; ?>
	</div>

	<?php endif; ?>
</article>

protected/views/post/index.php
<?php 
if (Yii::app()->request->getParam('category'))
	$contentTitle = Category::unfriendlyName(Yii::app()->request->getParam('category'));
else if (Yii::app()->request->getParam('year') && Yii::app()->request->getParam('month'))
	$contentTitle = 'Arquivo de "' . Yii::app()->request->getParam('year') . '/' . Yii::app()->request->getParam('month') . '"';
else if (Yii::app()->request->getParam('s'))
	$contentTitle = 'Resultados da busca por "' . Yii::app()->request->getParam('s') . '"';
else
	$contentTitle = ''; 

$this->pageTitle = 'Artigos' . ($contentTitle ? ' - ' . $contentTitle : '');
$this->sidebar = $this->renderPartial('_sidebar', array(), true);
?>

<?php $this->widget('zii.widgets.CListView', array(
	'id' => 'post-list',
	'dataProvider' => $dataProvider,
	'itemView' => '_view',
	'template' => "{items}\n{pager}",
	'pagerCssClass' => 'post-pager',
	'pager' => array(
		'header' => false,
		'prevPageLabel' => 'Mais recentes &rarr;',
		'nextPageLabel' => '&larr; Mais antigos',
		'previousPageCssClass' => 'next',
		'nextPageCssClass' => 'previous',
		'selectedPageCssClass' => 'active',
		'lastPageCssClass' => 'hidden',
		'firstPageCssClass' => 'hidden',
		'hiddenPageCssClass' => 'disabled',
		'htmlOptions' => array('class' => 'pager'),
	),
	'htmlOptions' => array(
		'class' => 'post-group'
	),
)); ?>

protected/views/post/view.php
<?php 
$this->pageTitle = CHtml::encode($post->title);
?>

<?php $this->renderPartial('_view', array('data' => $post, 'displayContent' => true, 'displayFullContent' => true, 'displayImg' => true, 'hideTitle' => true)); ?>